services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_data:/instance
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/tasks.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - NEXT_DISABLE_ESLINT=1
      - PORT=3000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: on-failure:5
    # # Add healthcheck to ensure container stays up
    # healthcheck:
    #   test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s

volumes:
  backend_data:
