"""add scheduled start/end to task

Revision ID: ad86da3fb3df
Revises: b513f2b5212a
Create Date: 2025-08-12 16:16:30.186139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad86da3fb3df'
down_revision = 'b513f2b5212a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('scheduled_end')
        batch_op.drop_column('scheduled_start')

    # ### end Alembic commands ###
