"""add user_preferences

Revision ID: fa35d5d14c27
Revises: ad86da3fb3df
Create Date: 2025-08-13 09:11:51.882097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fa35d5d14c27'
down_revision = 'ad86da3fb3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_off', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('workday_pref_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('workday_pref_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('focus_peak_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('focus_peak_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('default_duration_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('deadline_behavior', sa.Enum('EARLY', 'ON_TIME', 'LAST_MINUTE'), nullable=True))
        batch_op.add_column(sa.Column('flexibility', sa.Enum('LOW', 'MEDIUM', 'HIGH'), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_preferences_user_id', ['user_id'])
        batch_op.drop_column('preference_time')
        batch_op.drop_column('preferred_days_by_task')
        batch_op.drop_column('answers')
        batch_op.drop_column('preferred_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_days', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('answers', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferred_days_by_task', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preference_time', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('uq_user_preferences_user_id', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('flexibility')
        batch_op.drop_column('deadline_behavior')
        batch_op.drop_column('default_duration_minutes')
        batch_op.drop_column('focus_peak_end')
        batch_op.drop_column('focus_peak_start')
        batch_op.drop_column('workday_pref_end')
        batch_op.drop_column('workday_pref_start')
        batch_op.drop_column('days_off')

    # ### end Alembic commands ###
